---

services:
  npm_app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: npm_app
    ports:
      - '80:80' 
      - '443:443' 
      - '81:81' 
    environment:
      DB_MYSQL_HOST: "npm_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - npm_db

  npm_db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    container_name: npm_db
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - mysql:/var/lib/mysql

volumes:
    data:
    letsencrypt:
    mysql:

networks:
  default:
    name: int_dock_net