---

services:
  overseerr:
    image:  lscr.io/linuxserver/overseerr:latest
    container_name: overseerr 
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - overseerr:/config

volumes:
  overseerr:
    name: overseerr

networks:
  default:
    name: int_dock_net